# Generated by Django 2.0.4 on 2018-04-10 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_subscribers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Subscribers',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
