# Generated by Django 2.0.4 on 2018-04-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='track_text',
            field=models.TextField(max_length=1000),
        ),
    ]
